apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysecretdep
  name: mysecretdep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysecretdep
  template:
    metadata:
      labels:
        app: mysecretdep
    spec:
      containers:
      - image: postgres:latest
        name: postgres
        envFrom:
          - secretRef:
              name: mysecret
