apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: successresdep
  name: successresdep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: successresdep
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: successresdep
    spec:
      containers:
      - image: nginx:latest
        name: nginx
        resources:
          requests:
            memory: "200Mi"
            cpu: "0.5"
          limits:
            memory: "1Gi"
            cpu: "1"
