apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: egresspol
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: thinknyxone
  policyTypes:
    - Egress
  egress:
    - to:
      - podSelector:
          matchLabels:
            app: thinknyxtwo
    - ports:
        - port: 80
          protocol: TCP
