apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nodeaffinitytest
  name: nodeaffinitytest
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodeaffinitytest
  template:
    metadata:
      labels:
        app: nodeaffinitytest
    spec:
      containers:
      - image: nginx:latest
        name: nginx
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: environment
                  operator: In
                  values: 
                  - production
