apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: podantiaffinitytest
  name: podantiaffinitytest
spec:
  replicas: 2
  selector:
    matchLabels:
      app: podantiaffinitytest
  template:
    metadata:
      labels:
        app: podantiaffinitytest
    spec:
      containers:
      - image: nginx:latest
        name: nginx
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: kubernetes.io/hostname
              labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - testone
