apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: secretvol
  name: secretvol
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secretvol
  template:
    metadata:
      labels:
        app: secretvol
    spec:
      containers:
      - image: ubuntu:latest
        name: ubuntu
        command:
          - "sleep"
          - "3600"
        volumeMounts:
          - name: mysecretvol
            mountPath: /var/tmp
      volumes:
        - name: mysecretvol
          secret:
            secretName: mysecret
