apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfsvol
  labels:
    storage: nfsstorage
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 100Mi
  nfs:
    server: fs-08bbdf2516dd1305d.efs.us-east-1.amazonaws.com
    path: "/"
