apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfspvsc
  labels:
    app: demoapp
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  storageClassName: nfs-client
