apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: viewrole-binding
  namespace: testone
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: viewrole
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: myuser
